# Generated by Django 2.1.7 on 2022-04-30 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20220430_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopItem',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='ShopPost',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='ShopPurchase',
            new_name='Purchase',
        ),
    ]
