# Generated by Django 2.1.7 on 2022-04-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220430_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='user_id',
            new_name='user',
        ),
    ]
