# Generated by Django 2.1.7 on 2022-05-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220430_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='target_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('SUCCESS', '성공'), ('FUNDING', '진행중'), ('CANCEL', '취소'), ('CLOSE', '펀딩종료')], default='FUNDING', help_text='\n        SUCCESS는 펀딩이 성공적으로 진행되어 상품 준비단계까지 진행된 상태이며, \n        FUNDING는 펀딩이 진행중인 상태, \n        CLOSE는 펀딩이 종료된 상태, \n        CANCEL는 게시자가 확인되지 않아 글 작성이 취소된 상태이다.\n        결제는 DONATE단계에서 진행되며, CANCEL이 되면 결제 내역이 환불된다.\n    ', max_length=12),
        ),
    ]
