version: '3'

services:
  web:
    restart: always
    build: ./src
    expose:
      - "8000"
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    command: /usr/local/bin/gunicorn funding.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

volumes:
  web-django:
  web-static:
