# Generated by Django 2.1.7 on 2022-04-30 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220430_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='shop.ShopPost'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='shop_join_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppurchase',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='shop_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
