# Generated by Django 2.1.7 on 2022-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220427_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppurchase',
            name='status',
            field=models.CharField(choices=[('SUCCESS', '성공'), ('FAIL', '실패'), ('CANCEL', '취소/환불')], default='SUCCESS', max_length=12),
        ),
        migrations.AddField(
            model_name='shoppurchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shoppost',
            name='status',
            field=models.CharField(choices=[('SUCCESS', '성공'), ('FUNDING', '진행중'), ('CANCEL', '취소'), ('CLOSE', '펀딩종료')], default='FUNDING', help_text='\n        SUCCESS는 펀딩이 성공적으로 진행되어 상품 준비단계까지 진행된 상태이며, \n        FUNDING는 펀딩이 진행중인 상태, \n        CLOSE는 펀딩이 종료된 상태, \n        CANCEL는 펀딩 목표 금액을 넘지 못하여 펀딩이 취소된 상태를 의미한다. \n        결제는 DONATE단계에서 진행되며, CANCEL이 되면 결제 내역이 환불된다.\n    ', max_length=12),
        ),
    ]
