# Generated by Django 2.1.7 on 2022-04-24 08:30

from django.db import migrations, models
import funding.apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoppost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppost',
            name='final_date',
            field=models.CharField(max_length=25, validators=[funding.apps.core.validators.validate_date_component]),
        ),
    ]
